apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grade-api
  name: grade-api
spec:
  type: NodePort
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  selector:
    io.kompose.service: grade-api
status:
  loadBalancer: {}
